//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstinctWebServiceConnection.InstinctFraudCheckWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dectechsolutions.com/Instinct", ConfigurationName="InstinctFraudCheckWebService.OnlineFraudCheckSoap")]
    public interface OnlineFraudCheckSoap {
        
        // CODEGEN: Generating message contract since element name inputString from namespace http://dectechsolutions.com/Instinct is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dectechsolutions.com/Instinct/InstinctFraudCheck_String", ReplyAction="*")]
        InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_StringResponse InstinctFraudCheck_String(InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_StringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dectechsolutions.com/Instinct/InstinctFraudCheck_String", ReplyAction="*")]
        System.Threading.Tasks.Task<InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_StringResponse> InstinctFraudCheck_StringAsync(InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_StringRequest request);
        
        // CODEGEN: Generating message contract since element name inputXMLString from namespace http://dectechsolutions.com/Instinct is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dectechsolutions.com/Instinct/InstinctFraudCheck_XMLString", ReplyAction="*")]
        InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_XMLStringResponse InstinctFraudCheck_XMLString(InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_XMLStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dectechsolutions.com/Instinct/InstinctFraudCheck_XMLString", ReplyAction="*")]
        System.Threading.Tasks.Task<InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_XMLStringResponse> InstinctFraudCheck_XMLStringAsync(InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_XMLStringRequest request);
        
        // CODEGEN: Generating message contract since element name inputString from namespace http://dectechsolutions.com/Instinct is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dectechsolutions.com/Instinct/SubmitApplication_String", ReplyAction="*")]
        InstinctWebServiceConnection.InstinctFraudCheckWebService.SubmitApplication_StringResponse SubmitApplication_String(InstinctWebServiceConnection.InstinctFraudCheckWebService.SubmitApplication_StringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dectechsolutions.com/Instinct/SubmitApplication_String", ReplyAction="*")]
        System.Threading.Tasks.Task<InstinctWebServiceConnection.InstinctFraudCheckWebService.SubmitApplication_StringResponse> SubmitApplication_StringAsync(InstinctWebServiceConnection.InstinctFraudCheckWebService.SubmitApplication_StringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InstinctFraudCheck_StringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InstinctFraudCheck_String", Namespace="http://dectechsolutions.com/Instinct", Order=0)]
        public InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_StringRequestBody Body;
        
        public InstinctFraudCheck_StringRequest() {
        }
        
        public InstinctFraudCheck_StringRequest(InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_StringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dectechsolutions.com/Instinct")]
    public partial class InstinctFraudCheck_StringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputString;
        
        public InstinctFraudCheck_StringRequestBody() {
        }
        
        public InstinctFraudCheck_StringRequestBody(string inputString) {
            this.inputString = inputString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InstinctFraudCheck_StringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InstinctFraudCheck_StringResponse", Namespace="http://dectechsolutions.com/Instinct", Order=0)]
        public InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_StringResponseBody Body;
        
        public InstinctFraudCheck_StringResponse() {
        }
        
        public InstinctFraudCheck_StringResponse(InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_StringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dectechsolutions.com/Instinct")]
    public partial class InstinctFraudCheck_StringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InstinctFraudCheck_StringResult;
        
        public InstinctFraudCheck_StringResponseBody() {
        }
        
        public InstinctFraudCheck_StringResponseBody(string InstinctFraudCheck_StringResult) {
            this.InstinctFraudCheck_StringResult = InstinctFraudCheck_StringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InstinctFraudCheck_XMLStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InstinctFraudCheck_XMLString", Namespace="http://dectechsolutions.com/Instinct", Order=0)]
        public InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_XMLStringRequestBody Body;
        
        public InstinctFraudCheck_XMLStringRequest() {
        }
        
        public InstinctFraudCheck_XMLStringRequest(InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_XMLStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dectechsolutions.com/Instinct")]
    public partial class InstinctFraudCheck_XMLStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputXMLString;
        
        public InstinctFraudCheck_XMLStringRequestBody() {
        }
        
        public InstinctFraudCheck_XMLStringRequestBody(string inputXMLString) {
            this.inputXMLString = inputXMLString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InstinctFraudCheck_XMLStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InstinctFraudCheck_XMLStringResponse", Namespace="http://dectechsolutions.com/Instinct", Order=0)]
        public InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_XMLStringResponseBody Body;
        
        public InstinctFraudCheck_XMLStringResponse() {
        }
        
        public InstinctFraudCheck_XMLStringResponse(InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_XMLStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dectechsolutions.com/Instinct")]
    public partial class InstinctFraudCheck_XMLStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InstinctFraudCheck_XMLStringResult;
        
        public InstinctFraudCheck_XMLStringResponseBody() {
        }
        
        public InstinctFraudCheck_XMLStringResponseBody(string InstinctFraudCheck_XMLStringResult) {
            this.InstinctFraudCheck_XMLStringResult = InstinctFraudCheck_XMLStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitApplication_StringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitApplication_String", Namespace="http://dectechsolutions.com/Instinct", Order=0)]
        public InstinctWebServiceConnection.InstinctFraudCheckWebService.SubmitApplication_StringRequestBody Body;
        
        public SubmitApplication_StringRequest() {
        }
        
        public SubmitApplication_StringRequest(InstinctWebServiceConnection.InstinctFraudCheckWebService.SubmitApplication_StringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dectechsolutions.com/Instinct")]
    public partial class SubmitApplication_StringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputString;
        
        public SubmitApplication_StringRequestBody() {
        }
        
        public SubmitApplication_StringRequestBody(string inputString) {
            this.inputString = inputString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitApplication_StringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitApplication_StringResponse", Namespace="http://dectechsolutions.com/Instinct", Order=0)]
        public InstinctWebServiceConnection.InstinctFraudCheckWebService.SubmitApplication_StringResponseBody Body;
        
        public SubmitApplication_StringResponse() {
        }
        
        public SubmitApplication_StringResponse(InstinctWebServiceConnection.InstinctFraudCheckWebService.SubmitApplication_StringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dectechsolutions.com/Instinct")]
    public partial class SubmitApplication_StringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubmitApplication_StringResult;
        
        public SubmitApplication_StringResponseBody() {
        }
        
        public SubmitApplication_StringResponseBody(string SubmitApplication_StringResult) {
            this.SubmitApplication_StringResult = SubmitApplication_StringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OnlineFraudCheckSoapChannel : InstinctWebServiceConnection.InstinctFraudCheckWebService.OnlineFraudCheckSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnlineFraudCheckSoapClient : System.ServiceModel.ClientBase<InstinctWebServiceConnection.InstinctFraudCheckWebService.OnlineFraudCheckSoap>, InstinctWebServiceConnection.InstinctFraudCheckWebService.OnlineFraudCheckSoap {
        
        public OnlineFraudCheckSoapClient() {
        }
        
        public OnlineFraudCheckSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OnlineFraudCheckSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlineFraudCheckSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlineFraudCheckSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_StringResponse InstinctWebServiceConnection.InstinctFraudCheckWebService.OnlineFraudCheckSoap.InstinctFraudCheck_String(InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_StringRequest request) {
            return base.Channel.InstinctFraudCheck_String(request);
        }
        
        public string InstinctFraudCheck_String(string inputString) {
            InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_StringRequest inValue = new InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_StringRequest();
            inValue.Body = new InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_StringRequestBody();
            inValue.Body.inputString = inputString;
            InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_StringResponse retVal = ((InstinctWebServiceConnection.InstinctFraudCheckWebService.OnlineFraudCheckSoap)(this)).InstinctFraudCheck_String(inValue);
            return retVal.Body.InstinctFraudCheck_StringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_StringResponse> InstinctWebServiceConnection.InstinctFraudCheckWebService.OnlineFraudCheckSoap.InstinctFraudCheck_StringAsync(InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_StringRequest request) {
            return base.Channel.InstinctFraudCheck_StringAsync(request);
        }
        
        public System.Threading.Tasks.Task<InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_StringResponse> InstinctFraudCheck_StringAsync(string inputString) {
            InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_StringRequest inValue = new InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_StringRequest();
            inValue.Body = new InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_StringRequestBody();
            inValue.Body.inputString = inputString;
            return ((InstinctWebServiceConnection.InstinctFraudCheckWebService.OnlineFraudCheckSoap)(this)).InstinctFraudCheck_StringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_XMLStringResponse InstinctWebServiceConnection.InstinctFraudCheckWebService.OnlineFraudCheckSoap.InstinctFraudCheck_XMLString(InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_XMLStringRequest request) {
            return base.Channel.InstinctFraudCheck_XMLString(request);
        }
        
        public string InstinctFraudCheck_XMLString(string inputXMLString) {
            InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_XMLStringRequest inValue = new InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_XMLStringRequest();
            inValue.Body = new InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_XMLStringRequestBody();
            inValue.Body.inputXMLString = inputXMLString;
            InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_XMLStringResponse retVal = ((InstinctWebServiceConnection.InstinctFraudCheckWebService.OnlineFraudCheckSoap)(this)).InstinctFraudCheck_XMLString(inValue);
            return retVal.Body.InstinctFraudCheck_XMLStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_XMLStringResponse> InstinctWebServiceConnection.InstinctFraudCheckWebService.OnlineFraudCheckSoap.InstinctFraudCheck_XMLStringAsync(InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_XMLStringRequest request) {
            return base.Channel.InstinctFraudCheck_XMLStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_XMLStringResponse> InstinctFraudCheck_XMLStringAsync(string inputXMLString) {
            InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_XMLStringRequest inValue = new InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_XMLStringRequest();
            inValue.Body = new InstinctWebServiceConnection.InstinctFraudCheckWebService.InstinctFraudCheck_XMLStringRequestBody();
            inValue.Body.inputXMLString = inputXMLString;
            return ((InstinctWebServiceConnection.InstinctFraudCheckWebService.OnlineFraudCheckSoap)(this)).InstinctFraudCheck_XMLStringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InstinctWebServiceConnection.InstinctFraudCheckWebService.SubmitApplication_StringResponse InstinctWebServiceConnection.InstinctFraudCheckWebService.OnlineFraudCheckSoap.SubmitApplication_String(InstinctWebServiceConnection.InstinctFraudCheckWebService.SubmitApplication_StringRequest request) {
            return base.Channel.SubmitApplication_String(request);
        }
        
        public string SubmitApplication_String(string inputString) {
            InstinctWebServiceConnection.InstinctFraudCheckWebService.SubmitApplication_StringRequest inValue = new InstinctWebServiceConnection.InstinctFraudCheckWebService.SubmitApplication_StringRequest();
            inValue.Body = new InstinctWebServiceConnection.InstinctFraudCheckWebService.SubmitApplication_StringRequestBody();
            inValue.Body.inputString = inputString;
            InstinctWebServiceConnection.InstinctFraudCheckWebService.SubmitApplication_StringResponse retVal = ((InstinctWebServiceConnection.InstinctFraudCheckWebService.OnlineFraudCheckSoap)(this)).SubmitApplication_String(inValue);
            return retVal.Body.SubmitApplication_StringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InstinctWebServiceConnection.InstinctFraudCheckWebService.SubmitApplication_StringResponse> InstinctWebServiceConnection.InstinctFraudCheckWebService.OnlineFraudCheckSoap.SubmitApplication_StringAsync(InstinctWebServiceConnection.InstinctFraudCheckWebService.SubmitApplication_StringRequest request) {
            return base.Channel.SubmitApplication_StringAsync(request);
        }
        
        public System.Threading.Tasks.Task<InstinctWebServiceConnection.InstinctFraudCheckWebService.SubmitApplication_StringResponse> SubmitApplication_StringAsync(string inputString) {
            InstinctWebServiceConnection.InstinctFraudCheckWebService.SubmitApplication_StringRequest inValue = new InstinctWebServiceConnection.InstinctFraudCheckWebService.SubmitApplication_StringRequest();
            inValue.Body = new InstinctWebServiceConnection.InstinctFraudCheckWebService.SubmitApplication_StringRequestBody();
            inValue.Body.inputString = inputString;
            return ((InstinctWebServiceConnection.InstinctFraudCheckWebService.OnlineFraudCheckSoap)(this)).SubmitApplication_StringAsync(inValue);
        }
    }
}
